### ISSUE TITLE
BUG: resample audio

### ISSUE THREAD

**Issue by tzamalisp** [tzamalisp/crossai#25]
There is a bug in the resample function. This line of code:

* `secs = int(np.ceil(len(sig)/original_sr))`

forces the duration of the signal in the closest integer, disallowing intermediate real values, resulting in time-stretching or time compression.

**Comment by CaptainAlready** [comment]
@tzamalisp    this should fix things: https://github.com/AIoT-Group-UoP/crossai/blob/ccd135a41ad565abe0bf5018398d63ea79204a16/crossai/processing/_transform.py#L26C1-L28C49
